name: pusher
description: Push notification sender

publish_to: 'none'
version: 1.0.4+10

environment:
  sdk: ^3.3.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  window_manager: ^0.4.3 # Windows/Linux/macOS app window size controller

  flutter_statusbarcolor_ns: 0.6.0 # Native status bar controller (iOS Background color support)
    # git: # Android gradle namespace error fix
      # url: 'https://github.com/Schefferbird/flutter_statusbarcolor'
      # ref: 'ac7143a59a098d350bbd364880e619248be953f8'

  universal_platform: ^1.1.0

  pusher_core:
    path: local_plugins/pusher_core

  pusher_fl_core:
    path: local_plugins/pusher_fl_core

  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
