name: pusher
description: Push notification sender

publish_to: 'none'
version: 1.0.3+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_secure_storage: 9.2.4 # Sensitive data (tokens, cipher keys) container
  window_manager: 0.4.3 # Windows/Linux/macOS app window size controller

  flutter_statusbarcolor_ns: 0.6.0 # Native status bar controller (iOS Background color support)
    # git: # Android gradle namespace error fix
      # url: 'https://github.com/Schefferbird/flutter_statusbarcolor'
      # ref: 'ac7143a59a098d350bbd364880e619248be953f8'

  flutter_svg: 2.0.17 # SVG render engine
  dropdown_button2: 2.3.9 # Project select popup menu

  hive: 2.2.3 # NOSQL DB
  hive_flutter: 1.1.0

  pusher_core:
    path: local_plugins/pusher_core

  pusher_fl_core:
    path: local_plugins/pusher_fl_core

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
