include: package:lints/recommended.yaml

linter:
  rules:
    prefer_relative_imports: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_function_literals_in_foreach_calls: true
    avoid_print: false
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    hash_and_equals: true
    no_duplicate_case_values: true
    no_self_assignments: true
    camel_case_extensions: true
    camel_case_types: true
    do_not_use_environment: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    prefer_const_constructors: true
    prefer_interpolation_to_compose_strings: false
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    provide_deprecation_message: true
    unnecessary_new: true