name: pusher_fl_core
description: "Pusher fully cross-platform Flutter core"
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Native payload dependencies (Fully cross-platform)
  shared_preferences: ^2.2.3 # Last 3.3.0 version - 2.2.3
  flutter_secure_storage: ^9.2.4

  # Flutter packages (Fully cross-platform)
  flutter_svg: ^2.0.10+1 # SVG render engine # Last 3.3.0 version - 2.0.10+1
  hive_flutter: ^1.1.0 # NOSQL DB

  pusher_core:
    path: ../pusher_core

  intl: any

# Intl hint https://pub.dev/packages/intl_utils
flutter_intl:
  enabled: true
  class_name: FlCoreLocalizations
  main_locale: en
  arb_dir: lib/src/l10n
  output_dir: lib/src/generated

flutter:
  uses-material-design: true
  assets:
    - assets/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

  # Setup: flutter pub global flutter_gen
  flutter_gen: ^5.10.0 # Assets map generator (from flutter core dir: fluttergen -c pucbspec.yaml) (from root project dir: fluttergen -c local_plugins/pusher_fl_core/pubspec.yaml)

flutter_gen:

  assets:
    # exclude:
    # - folder-your-want-to-exclude/**
    # - specified-asset.jpg
    outputs:
      class_name: RAssets
      package_parameter_enabled: true # Package assets outside access

  integrations:
    image: false
    flutter_svg: false

  output: lib/src/generated