name: pusher_fl_core
description: "Pusher fully cross-platform Flutter core"
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  # Native payload dependencies
  shared_preferences: 2.5.1

  pusher_core:
    path: ../pusher_core

  flutter_svg: 2.0.17 # SVG render engine

  intl: ^0.19.0

# Intl hint https://pub.dev/packages/intl_utils
flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/src/l10n
  output_dir: lib/src/generated

flutter:
  uses-material-design: true
  assets:
    - assets/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

  # Setup: flutter pub global flutter_gen
  flutter_gen: 5.8.0 # Assets map generator (fluttergen -c pubspec.yaml)

flutter_gen:

  assets:
    # exclude:
    # - folder-your-want-to-exclude/**
    # - specified-asset.jpg
    outputs:
      class_name: R
      package_parameter_enabled: true # Package assets outside access

  integrations:
    image: false
    flutter_svg: false

  output: lib/src/generated